// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVYL59cvcMcL-0qDCCHrom-yhB4QlkhPI',
    appId: '1:402596558785:web:2088a85189ae5891fd6140',
    messagingSenderId: '402596558785',
    projectId: 'familycal-prod',
    authDomain: 'familycal-prod.firebaseapp.com',
    storageBucket: 'familycal-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdlXAO607lbboJc3GDuzZkIYKrLNhBDg',
    appId: '1:402596558785:android:44373b3dd0e4019ffd6140',
    messagingSenderId: '402596558785',
    projectId: 'familycal-prod',
    storageBucket: 'familycal-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1PiHx6mJTpNr1opYTQ1V3iYpIYitq1Us',
    appId: '1:402596558785:ios:b0c25ea92318079afd6140',
    messagingSenderId: '402596558785',
    projectId: 'familycal-prod',
    storageBucket: 'familycal-prod.firebasestorage.app',
    iosBundleId: 'com.example.familycal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1PiHx6mJTpNr1opYTQ1V3iYpIYitq1Us',
    appId: '1:402596558785:ios:b0c25ea92318079afd6140',
    messagingSenderId: '402596558785',
    projectId: 'familycal-prod',
    storageBucket: 'familycal-prod.firebasestorage.app',
    iosBundleId: 'com.example.familycal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVYL59cvcMcL-0qDCCHrom-yhB4QlkhPI',
    appId: '1:402596558785:web:a8bdf070b3c5d1cffd6140',
    messagingSenderId: '402596558785',
    projectId: 'familycal-prod',
    authDomain: 'familycal-prod.firebaseapp.com',
    storageBucket: 'familycal-prod.firebasestorage.app',
  );
}
