name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure no merge conflict markers
        run: |
          if git -C .. grep -n '^[<=>]\{7\} ' -- ':!firebase/functions/node_modules/**'; then
            echo "::error::Merge conflict markers detected. Please resolve them before merging."
            exit 1
          fi

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.16.5'

      - name: Flutter pub get
        run: flutter pub get

      - name: Flutter format check
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test --no-pub
